### ISSUE TITLE
Rename Language Specific Libraries

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/.eclipsefdn#14]
The various language specific libraries had "sdk" in their name but this is only one library that would be included in a Software Development Kit. The change will be to rename the following projects:
- uprotocol-sdk-java --> uprotocol-java
- uprotocol-sdk-python --> uprotocol-python
- uprotocol-sdk-cpp --> uprotocol-cpp
- uprotocol-sdk-rust --> uprotocol-rust

NOTE: We will update first the python to test affect to the forks (hopefully only requiring an update to the git remote command).

**Comment by netomi** [comment]
in order to rename repos with the self-service, just give the repo a new name and include the previous one as alias like that:

```
    orgs.newRepo('uprotocol-java') {
      aliases: ["uprotocol-sdk-java"],
      allow_merge_commit: true,
      allow_update_branch: false,
      delete_branch_on_merge: false,
      description: "uProtocol Java SDK",
      web_commit_signoff_required: false,
      workflows+: {
        actions_can_approve_pull_request_reviews: false,
      },
    },
```

**Comment by stevenhartley** [comment]
Done

**Comment by netomi** [comment]
so all work has been done here so we can close it.
